server:
  port: 6666
spring:
  datasource:
    # Oracle 核心配置（根据你的实际环境调整）
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
#    username: tuster_test
    username: tuster_test
    password: visit
    driver-class-name: oracle.jdbc.OracleDriver

  servlet:
    # 文件上传
    multipart:
      # 单个上传文件的最大允许大小
      max-file-size: 20MB
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 20MB

redis:
  host: localhost  # Redis服务器地址
  port: 6379       # Redis服务器端口
  password:        # Redis服务器密码（如果没有密码，留空）
  database: 0      # Redis数据库索引（默认为0）
  timeout: 3000ms  # 连接超时时间（毫秒）
  lettuce:
    pool:
      max-active: 8    # 连接池最大连接数
      max-idle: 8      # 连接池最大空闲连接数
      min-idle: 0      # 连接池最小空闲连接数
      max-wait: -1ms   # 连接池最大阻塞等待时间（-1表示无限制）

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


oss:
  accessKey: 2PekK14uCt-frzDjXaTyEC_t2th8cClJHmHYh2G-
  secretKey: vQW4agExPi2tl0qN8fUSGAAOnHcxva0Wd4fXxCGp
  bucket: employee-data-platform